<a href="https://colab.research.google.com/github/ritikrai00/pandas_notes/blob/master/pandascs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd

In [35]:
df=pd.read_csv('/content/data.csv')
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [36]:
df.shape

(33010, 85)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33010 entries, 0 to 33009
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              33010 non-null  int64
 1   MainBranch              33010 non-null  object
 2   Hobbyist                33010 non-null  object
 3   OpenSourcer             33010 non-null  object
 4   OpenSource              32271 non-null  object
 5   Employment              32382 non-null  object
 6   Country                 33010 non-null  object
 7   Student                 32367 non-null  object
 8   EdLevel                 32126 non-null  object
 9   UndergradMajor          28151 non-null  object
 10  EduOther                31332 non-null  object
 11  OrgSize                 26700 non-null  object
 12  DevType                 30269 non-null  object
 13  YearsCode               32726 non-null  object
 14  Age1stCode              32608 non-null  object
 15  YearsCodePro            27617 non-null  object
 16  CareerSat               27181 non-null  object
 17  JobSat                  26487 non-null  object
 18  MgrIdiot                22738 non-null  object
 19  MgrMoney                22743 non-null  object
 20  MgrWant                 22764 non-null  object
 21  JobSeek                 30083 non-null  object
 22  LastHireDate            29809 non-null  object
 23  LastInt                 25003 non-null  object
 24  FizzBuzz                26627 non-null  object
 25  JobFactors              29647 non-null  object
 26  ResumeUpdate            29118 non-null  object
 27  CurrencySymbol          26636 non-null  object
 28  CurrencyDesc            26636 non-null  object
 29  CompTotal               20822 non-null  float64
 30  CompFreq                23610 non-null  object
 31  ConvertedComp           20781 non-null  float64
 32  WorkWeekHrs             24068 non-null  float64
 33  WorkPlan                25719 non-null  object
 34  WorkChallenge           25452 non-null  object
 35  WorkRemote              26214 non-null  object
 36  WorkLoc                 26148 non-null  object
 37  ImpSyn                  26772 non-null  object
 38  CodeRev                 26246 non-null  object
 39  CodeRevHrs              18561 non-null  float64
 40  UnitTests               23390 non-null  object
 41  PurchaseHow             22794 non-null  object
 42  PurchaseWhat            23152 non-null  object
 43  LanguageWorkedWith      32613 non-null  object
 44  LanguageDesireNextYear  31316 non-null  object
 45  DatabaseWorkedWith      28300 non-null  object
 46  DatabaseDesireNextYear  25754 non-null  object
 47  PlatformWorkedWith      30057 non-null  object
 48  PlatformDesireNextYear  28838 non-null  object
 49  WebFrameWorkedWith      24225 non-null  object
 50  WebFrameDesireNextYear  23402 non-null  object
 51  MiscTechWorkedWith      22184 non-null  object
 52  MiscTechDesireNextYear  24078 non-null  object
 53  DevEnviron              32524 non-null  object
 54  OpSys                   32701 non-null  object
 55  Containers              31795 non-null  object
 56  BlockchainOrg           17934 non-null  object
 57  BlockchainIs            22474 non-null  object
 58  BetterLife              32105 non-null  object
 59  ITperson                32418 non-null  object
 60  OffOn                   32226 non-null  object
 61  SocialMedia             31491 non-null  object
 62  Extraversion            32457 non-null  object
 63  ScreenName              29899 non-null  object
 64  SOVisit1st              31241 non-null  object
 65  SOVisitFreq             32835 non-null  object
 66  SOVisitTo               32788 non-null  object
 67  SOFindAnswer            32682 non-null  object
 68  SOTimeSaved             32166 non-null  object
 69  SOHowMuchTime           25463 non-null  object
 70  SOAccount               32698 non-null  object
 71  SOPartFreq              27851 non-null  object
 72  SOJobs                  32766 non-null  object
 73  EntTeams                32676 non-null  object
 74  SOComm                  32794 non-null  object
 75  WelcomeChange           31936 non-null  object
 76  SONewContent            25839 non-null  object
 77  Age                     29504 non-null  float64
 78  Gender                  31778 non-null  object
 79  Trans                   31137 non-null  object
 80  Sexuality               28440 non-null  object
 81  Ethnicity               28528 non-null  object
 82  Dependents              30895 non-null  object
 83  SurveyLength            32337 non-null  object
 84  SurveyEase              32393 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 21.4+ MB

In [38]:
pd.set_option('display.max_columns', 85)

In [39]:
df.head()

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [40]:
type(df)

pandas.core.frame.DataFrame

#accessing col

In [41]:
df['Age'] #df.Age

0        14.0
1        19.0
2        28.0
3        22.0
4        30.0
         ...
33005    26.0
33006    24.0
33007    24.0
33008    38.0
33009    25.0
Name: Age, Length: 33010, dtype: float64

In [42]:
type(df['Age'])

pandas.core.series.Series

In [43]:
df[['Age','Country']]

        Age                 Country
0      14.0          United Kingdom
1      19.0  Bosnia and Herzegovina
2      28.0                Thailand
3      22.0           United States
4      30.0                 Ukraine
...     ...                     ...
33005  26.0                 Belarus
33006  24.0                  France
33007  24.0                 Germany
33008  38.0               Australia
33009  25.0                   India

[33010 rows x 2 columns]

In [44]:
df.columns

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [45]:
df.head(2)

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

#accessing rows--loc, iloc[row,col]

In [46]:
df.iloc[1]

Respondent                                                      2
MainBranch                 I am a student who is learning to code
Hobbyist                                                       No
OpenSourcer                               Less than once per year
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 1, Length: 85, dtype: object

In [47]:
type(df.iloc[0])

pandas.core.series.Series

In [48]:
df.iloc[[0,1]]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [49]:
df.iloc[[0,1],0]

0    1
1    2
Name: Respondent, dtype: int64

In [50]:
df.iloc[[0,1],[0,1]]

   Respondent                              MainBranch
0           1  I am a student who is learning to code
1           2  I am a student who is learning to code

In [51]:
df.loc[0]

Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object

In [52]:
df.loc[[0,1]]

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [53]:
df.loc[[0,1],'Respondent']

0    1
1    2
Name: Respondent, dtype: int64

In [54]:
df.loc[[0,1],['Respondent','MainBranch']]

   Respondent                              MainBranch
0           1  I am a student who is learning to code
1           2  I am a student who is learning to code

In [55]:
df['Hobbyist']

0        Yes
1         No
2        Yes
3         No
4        Yes
        ...
33005    Yes
33006    Yes
33007    Yes
33008     No
33009     No
Name: Hobbyist, Length: 33010, dtype: object

In [56]:
df['Hobbyist'].value_counts()

Hobbyist
Yes    26486
No      6524
Name: count, dtype: int64

In [57]:
df.loc[0:2,'Hobbyist':'Employment'] #last val is inclusive

,Hobbyist,OpenSourcer,OpenSource,Employment
0,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work"
1,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work"
2,Yes,Never,The quality of OSS and closed source software ...,Employed full-time

In [58]:
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33005,33212,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,Belarus,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,"1,000 to 4,999 employees","Developer, front-end;Developer, full-stack;Edu...",15,11,6,Slightly satisfied,Slightly satisfied,Very confident,Yes,Not sure,"Iâ€™m not actively looking, but I am open to n...",More than 4 years ago,Write any code;Interview with people in peer r...,No,"Languages, frameworks, and other technologies ...",I heard about a job opportunity (from a recrui...,USD,United States dollar,2700.0,Monthly,32400.0,40.0,There is a schedule and/or spec (made by me or...,Meetings,A few days each month,Office,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers typically have the most influence o...,I have some influence,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...,C#;HTML/CSS;JavaScript;Python;TypeScript,MongoDB;Microsoft SQL Server;Redis,MongoDB;Microsoft SQL Server;Redis,Heroku;Windows,Heroku;Windows,Angular/Angular.js;ASP.NET;Express;jQuery;Reac...,Angular/Angular.js;ASP.NET;Express;jQuery;Reac...,.NET;.NET Core;Node.js,.NET;.NET Core;Node.js;React Native,Visual Studio;Visual Studio Code,Windows,"Outside of work, for personal projects",Non-currency applications of blockchain,Useful for immutable record keeping outside of...,Yes,Yes,No,Instagram,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Contribute ...,1-2 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
33006,33213,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,France,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,500 to 999 employees,"Data or business analyst;Engineer, data",8,15,4,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,I had a negative experience or interaction at ...,EUR,European Euro,46000.0,Yearly,52704.0,38.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",3.0,"Yes, it's part of our process",Developers typically have the most influence o...,I have a great deal of influence,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,Python;Scala;SQL,Cassandra;MongoDB;MySQL;SQLite,Cassandra;Elasticsearch;Other(s):,iOS;Linux;MacOS;Slack,Google Cloud Platform;Linux;Slack,Angular/Angular.js;Flask;jQuery,NaN,Ansible;Apache Spark;Hadoop;TensorFlow,Apache Spark,Atom;IntelliJ,Linux-based,Development;Testing;Production;Outside of work...,Not at all,An irresponsible use of resources,NaN,SIGH,Yes,Reddit,In real life (in person),Username,2012,A few times per week,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
33007,33214,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Germany,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",20 to 99 employees,"Designer;Developer, back-end;Developer, front-...",5,18,2,Very dissatisfied,Very dissatisfied,Very confident,No,Yes,"Iâ€™m not actively looking, but I am open to n...",Less than a year ago,NaN,No,Financial performance or funding status of the...,I was preparing for a job search,EUR,European Euro,3000.0,Monthly,41244.0,40.0,There is a schedule and/or spec (made by me or...,Inadequate access to necessary tools;Lack of s...,Less than once per month / Never,Home,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the deve...",Developers typically have the most influence o...,I have some influence,Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...,Bash/Shell/PowerShell;C;C++;C#;Go;HTML/CSS;Jav...,MariaDB;MySQL;SQLite,MongoDB;MySQL,Raspberry Pi,Android;Linux;Windows,ASP.NET;jQuery,jQuery;Ruby on Rails;Vue.js,.NET,Unreal Engine,Eclipse;Notepad++;Visual Studio,Windows,"Outside of work, for personal projects",Non-currency applications of blockchain,"Useful for decentralized currency (i.e., Bitcoin)",Yes,Yes,Yes,YouTube,In real life (in person),UserID,2016,Multiple times per day,Find answers to specific questions;Learn how t...,More than 10 times per week,Stack Overflow was slightly faster,31-60 minutes,Yes,Daily or almost daily,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat more welcome now than last year,Industry news about technologies you're intere...,24.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
33008,33215,I am a developer by profession,No,Less than once per year,NaN,Employed full-time,Australia,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken a part-time in-person course in programm...,"10,000 or more employees","Developer, full-stack;Product manager",24,12,20,Slightly satisfied,Slightly satisfied,Somewhat confident,Yes,I am already a manager,"Iâ€™m not actively looking, but I am open to n...",More than 4 years ago,Interview with people in senior / management r...,No,"Languages, frameworks, and other technologies ...","Something else changed (education, award, medi...",AUD,Australian dollar,120000.0,Yearly,87036.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,Less than once per month / Never,Home,Far above average,"Yes, because I see value in code review",2.0,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have little or no influence,HTML/CSS;JavaScript;SQL;Other(s):,C#;HTML/CSS;JavaScript;SQL;Other(s):,Microsoft SQL Server,Microsoft SQL Server,Windows,Windows,ASP.NET,ASP.NET;jQuery,.NET,.NET,Visual Studio,Windows,I do not use containers,Not at all,Useful for immutable record keeping outside of...,Yes,SIGH,Yes,Facebook,Online,UserID,2009,Daily or almost daily,Find answers to specific questions;Contribute ...,1-2 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per week,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Somewhat less welcome now than last year,NaN,38.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
33009,33216,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"5,000 to 9,999 employees","Developer, back-end;Developer, desktop or ente...",4,12,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Yes,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,Write any code;Interview with people in senior...,No,Financial performance or funding status of the...,I was preparing for a job search,INR,Indian rupee,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have little or no influence,C#;JavaScript,JavaScript,NaN,NaN,Windows,Android;iOS,Angular/Angular.js,Angular/Angular.js,.NET;.NET Core,.NET;.NET Core,Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,NaN,Yes,Yes,Yes,Instagram,In real life (in person),Username,2015,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in len,NaN

In [59]:
people_info = {
    'first_name': ['John', 'Jane', 'Peter'],
    'last_name': ['Doe', 'Smith', 'Jones'],
    'email': ['john.doe@example.com', 'jane.smith@example.com', 'peter.jones@example.com']
}

In [60]:
df_sample=pd.DataFrame(people_info)
df_sample

  first_name last_name                    email
0       John       Doe     john.doe@example.com
1       Jane     Smith   jane.smith@example.com
2      Peter     Jones  peter.jones@example.com

In [61]:
df_sample.index

RangeIndex(start=0, stop=3, step=1)

In [62]:
df_sample.set_index('email',inplace=True)

In [63]:
df_sample

                        first_name last_name
email
john.doe@example.com          John       Doe
jane.smith@example.com        Jane     Smith
peter.jones@example.com      Peter     Jones

In [64]:
df_sample.index

Index(['john.doe@example.com', 'jane.smith@example.com',
       'peter.jones@example.com'],
      dtype='object', name='email')

In [65]:
df_sample.loc['john.doe@example.com','last_name']

'Doe'

In [66]:
df_sample.iloc[0,1]

'Doe'

In [67]:
df_sample.reset_index(inplace=True)
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [68]:
df=pd.read_csv('/content/data.csv',index_col='Respondent')
df.head()

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",100 to 499 employees,"Designer;Developer, back-end;Developer, front-...",3,22,1,Slightly satisfied,Slightly satisfied,Not at all confident,Not sure,Not sure,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,Interview with people in peer roles,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,THB,Thai baht,23000.0,Monthly,8820.0,40.0,There's no schedule or spec; I work on what se...,Distracting work environment;Inadequate access...,Less than once per month / Never,Home,Average,No,NaN,"No, but I think we should",Not sure,I have little or no influence,HTML/CSS,Elixir;HTML/CSS,PostgreSQL,PostgreSQL,NaN,NaN,NaN,Other(s):,NaN,NaN,Vim;Visual Studio Code,Linux-based,I do not use containers,NaN,NaN,Yes,Yes,Yes,Reddit,In real life (in person),Username,2011,A few times per week,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, full-stack",3,16,Less than 1 year,Very satisfied,Slightly satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write code by hand (e.g., on a whiteboard);Int...",No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,61000.0,Yearly,61000.0,80.0,There's no schedule or spec; I work on what se...,NaN,Less than once per month / Never,Home,A little below average,No,NaN,"No, but I think we should",Developers typically have the most influence o...,I have little or no influence,C;C++;C#;Python;SQL,C;C#;JavaScript;SQL,MySQL;SQLite,MySQL;SQLite,Linux;Windows,Linux;Windows,NaN,NaN,.NET,.NET,Eclipse;Vim;Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,"Useful for decentralized currency (i.e., Bitcoin)",Yes,SIGH,Yes,Reddit,In real life (in person),Username,2014,Daily or almost daily,Find answers to specific questions;Pass the ti...,1-2 times per week,Stack Overflow was much faster,31-60 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Academic researcher;Developer, desktop or ente...",16,14,9,Very dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,No,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,"Industry that I'd be working in;Languages, fra...",I was preparing for a job search,UAH,Ukrainian hryvnia,NaN,NaN,NaN,55.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,A few days each month,Office,A little above average,"Yes, because I see value in code review",NaN,"Yes, it's part of our process",Not sure,I have little or no influence,C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA,HTML/CSS;Java;JavaScript;SQL;WebAssembly,Couchbase;MongoDB;MySQL;Oracle;PostgreSQL;SQLite,Couchbase;Firebase;MongoDB;MySQL;Oracle;Postgr...,Android;Linux;MacOS;Slack;Windows,Android;Docker;Kubernetes;Linux;Slack,Django;Express;Flask;jQuery;React.js;Spring,Flask;jQuery;React.js;Spring,Cordova;Node.js,Apache Spark;Hadoop;Node.js;React Native,IntelliJ;Notepad++;Vim,Linux-based,"Outside of work, for personal projects",Not at all,NaN,Yes,Also Yes,Yes,Facebook,In real life (in person),Username,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","Yes, definitely",Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy

In [69]:
df.loc[1]

MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
Employment                 Not employed, and not looking for work
                                      ...
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 1, Length: 84, dtype: object

In [70]:
#sort index==> df.sort_index(inplace)


> Filtering

In [71]:
df_sample['last_name']=='Doe'

0     True
1    False
2    False
Name: last_name, dtype: bool

In [72]:
df_sample[df_sample['last_name']=='Doe']

                  email first_name last_name
0  john.doe@example.com       John       Doe

In [73]:
df_sample.loc[df_sample['last_name']=='Doe']

                  email first_name last_name
0  john.doe@example.com       John       Doe

In [74]:
df_sample.loc[df_sample['last_name']=='Doe','email']

0    john.doe@example.com
Name: email, dtype: object

In [75]:
df_sample.loc[(df_sample['last_name']=='Doe') & (df_sample['first_name']=='John')]

                  email first_name last_name
0  john.doe@example.com       John       Doe

In [76]:
df_sample.loc[(df_sample['last_name']=='Doe') | (df_sample['first_name']=='John')]

                  email first_name last_name
0  john.doe@example.com       John       Doe

In [77]:
df_sample.loc[~((df_sample['last_name']=='Doe') | (df_sample['first_name']=='John'))]

                     email first_name last_name
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [78]:
df.loc[df['ConvertedComp']>70000,['Country','LanguageWorkedWith','ConvertedComp']]

,Country,LanguageWorkedWith,ConvertedComp
Respondent,,,
6,Canada,Java;R;SQL,366420.0
9,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...,95179.0
13,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,90000.0
16,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...,455352.0
22,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...,103000.0
...,...,...,...
33192,Sweden,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,662796.0
33199,United States,Java;Kotlin;Python,204000.0
33206,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...,392544.0
33207,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;SQL,75000.0
33215,Australia,HTML/CSS;JavaScript;SQL;Other(s):,87036.0

In [79]:
countries=['United States','India','United Kingdom','Germany','Canada']

In [80]:
filt=df['Country'].isin(countries)
df.loc[filt,'Country']

Respondent
1        United Kingdom
4         United States
6                Canada
8                 India
10                India
              ...
33205             India
33206    United Kingdom
33207     United States
33214           Germany
33216             India
Name: Country, Length: 16760, dtype: object

In [81]:
df['LanguageWorkedWith']

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
3                                                 HTML/CSS
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
                               ...
33212    Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;S...
33213    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
33214    Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
33215                    HTML/CSS;JavaScript;SQL;Other(s):
33216                                        C#;JavaScript
Name: LanguageWorkedWith, Length: 33010, dtype: object

In [82]:
filt=df['LanguageWorkedWith'].str.contains('Python',na=False)
df.loc[filt,'LanguageWorkedWith']

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
8        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
33202              HTML/CSS;Java;JavaScript;PHP;Python;SQL
33204              Java;JavaScript;Kotlin;Python;Scala;SQL
33208                                         C;C++;Python
33213    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
33214    Bash/Shell/PowerShell;C++;C#;HTML/CSS;JavaScri...
Name: LanguageWorkedWith, Length: 13631, dtype: object

In [83]:
df_sample.columns

Index(['email', 'first_name', 'last_name'], dtype='object')

In [84]:
df_sample.columns=['email','first','last']
df_sample

                     email  first   last
0     john.doe@example.com   John    Doe
1   jane.smith@example.com   Jane  Smith
2  peter.jones@example.com  Peter  Jones

In [85]:
df_sample.columns=[x.upper() for x in df_sample.columns]
df_sample.columns

Index(['EMAIL', 'FIRST', 'LAST'], dtype='object')

In [86]:
df_sample.columns=df_sample.columns.str.replace(' ','_')
df_sample.columns

Index(['EMAIL', 'FIRST', 'LAST'], dtype='object')

In [87]:
df_sample.columns=[x.lower() for x in df_sample.columns]
df_sample.columns

Index(['email', 'first', 'last'], dtype='object')

In [88]:
df_sample.rename(columns={'first':'first_name','last':'last_name'},inplace=True)
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [89]:
df_sample.loc[0]=['john.smith@example.com','John','Smith']
df_sample

                     email first_name last_name
0   john.smith@example.com       John     Smith
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [90]:
df_sample.loc[0,['last_name','email']]=['Doe','john.doe@example.com']
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [91]:
df_sample.at[2,'last_name']='Smith'
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Smith

In [92]:
df_sample.loc[2,'last_name']='Jones'
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [93]:
df_sample['email']=df_sample['email'].str.lower()
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [94]:
#changing multiple rows values
#apply
#map
#replace

In [95]:
#apply on series
df_sample['email'].apply(len)

0    20
1    22
2    23
Name: email, dtype: int64

In [96]:
def update_email(email):
  return email.upper()

In [97]:
df_sample['email']=df_sample['email'].apply(update_email)
df_sample

                     email first_name last_name
0     JOHN.DOE@EXAMPLE.COM       John       Doe
1   JANE.SMITH@EXAMPLE.COM       Jane     Smith
2  PETER.JONES@EXAMPLE.COM      Peter     Jones

In [98]:
df_sample['email']=df_sample['email'].apply(lambda x:x.lower())
df_sample

                     email first_name last_name
0     john.doe@example.com       John       Doe
1   jane.smith@example.com       Jane     Smith
2  peter.jones@example.com      Peter     Jones

In [99]:
#apply on df
df_sample.apply(len)

email         3
first_name    3
last_name     3
dtype: int64

In [100]:
df_sample.apply(len,axis='columns')

0    3
1    3
2    3
dtype: int64

In [101]:
df_sample.apply(pd.Series.min)

email         jane.smith@example.com
first_name                      Jane
last_name                        Doe
dtype: object

In [102]:
df_sample.apply(lambda x:x.min()) #apply on df- applies to each series of df

email         jane.smith@example.com
first_name                      Jane
last_name                        Doe
dtype: object

In [103]:
#map-works on entire df
df_sample.map(len)

   email  first_name  last_name
0     20           4          3
1     22           4          5
2     23           5          5

In [104]:
df_sample=df_sample.map(str.lower)
df_sample

                     email first_name last_name
0     john.doe@example.com       john       doe
1   jane.smith@example.com       jane     smith
2  peter.jones@example.com      peter     jones

In [105]:
#map also work on series- used to substitute each value with another value in a series
df_sample['first_name']=df_sample['first_name'].map({'john':'John','jane':'Jane','peter':'Peter'})

In [106]:
df_sample

                     email first_name last_name
0     john.doe@example.com       John       doe
1   jane.smith@example.com       Jane     smith
2  peter.jones@example.com      Peter     jones

In [107]:
df_sample['first_name']=df_sample['first_name'].str.lower()
df_sample

                     email first_name last_name
0     john.doe@example.com       john       doe
1   jane.smith@example.com       jane     smith
2  peter.jones@example.com      peter     jones

In [108]:
#problem with map
df_sample['first_name'].map({'john':'John','jane':'Jane'})

0    John
1    Jane
2     NaN
Name: first_name, dtype: object

In [109]:
#so we use replace
df_sample['first_name'].replace({'john':'John','jane':'Jane'})

0     John
1     Jane
2    peter
Name: first_name, dtype: object

In [110]:
#df.rename(columns={'ConvertedComp':'SalaryUSD'},inplace=True)
#df['SalaryUSD']

In [111]:
df['Hobbyist']

Respondent
1        Yes
2         No
3        Yes
4         No
5        Yes
        ...
33212    Yes
33213    Yes
33214    Yes
33215     No
33216     No
Name: Hobbyist, Length: 33010, dtype: object

In [112]:
df['Hobbyist']=df['Hobbyist'].map({'Yes':True,'No':False})
df.head(2)
#use replace if other values are present

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,True,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,False,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [113]:
#add/del rows/col
df_sample['full_name']=df_sample['first_name']+' '+df_sample['last_name']
df_sample

                     email first_name last_name    full_name
0     john.doe@example.com       john       doe     john doe
1   jane.smith@example.com       jane     smith   jane smith
2  peter.jones@example.com      peter     jones  peter jones

In [114]:
df_sample.drop(columns=['first_name','last_name'],inplace=True)
df_sample

                     email    full_name
0     john.doe@example.com     john doe
1   jane.smith@example.com   jane smith
2  peter.jones@example.com  peter jones

In [115]:
df_sample[['first','last']]=df_sample['full_name'].str.split(' ',expand=True)
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones

In [116]:
df_sample._append({'first':'Tony'},ignore_index=True)

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
3                      NaN          NaN   Tony    NaN

In [117]:
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones

In [118]:
x=pd.DataFrame({'first':['Tony']})

In [119]:
pd.concat([df_sample,x],ignore_index=True)

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
3                      NaN          NaN   Tony    NaN

In [120]:
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones

In [121]:
people_info2 = {
    'first': ['Clark', 'Bruce'],
    'last': ['Kent', 'Wayne'],
    'email': ['clark.kent@example.com', 'bruce.wayne@example.com']
}
df_sample2=pd.DataFrame(people_info2)
df_sample2

   first   last                    email
0  Clark   Kent   clark.kent@example.com
1  Bruce  Wayne  bruce.wayne@example.com

In [122]:
df_sample=pd.concat([df_sample,df_sample2],ignore_index=True)
# or df_sample._append(df_sample2,ignore_index=True)

In [123]:
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
3   clark.kent@example.com          NaN  Clark   Kent
4  bruce.wayne@example.com          NaN  Bruce  Wayne

In [124]:
df_sample.drop(index=3,inplace=True)

In [125]:
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
4  bruce.wayne@example.com          NaN  Bruce  Wayne

In [126]:
df_sample=df_sample.drop(index=df_sample[df_sample['last']=='Wayne'].index)

In [127]:
#sorting
df_sample=df_sample._append({'email':'tony.doe@e.com','full_name':'tony doe','first':'tony','last':'doe'},ignore_index=True)
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
3           tony.doe@e.com     tony doe   tony    doe

In [128]:
df_sample.sort_values(by='last',ascending=False)

                     email    full_name  first   last
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
0     john.doe@example.com     john doe   john    doe
3           tony.doe@e.com     tony doe   tony    doe

In [129]:
df_sample.sort_values(by=['last','first'],ascending=False)

                     email    full_name  first   last
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
3           tony.doe@e.com     tony doe   tony    doe
0     john.doe@example.com     john doe   john    doe

In [130]:
df_sample.sort_values(by=['last','first'],ascending=[False,True],inplace=True)
df_sample

                     email    full_name  first   last
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
0     john.doe@example.com     john doe   john    doe
3           tony.doe@e.com     tony doe   tony    doe

In [131]:
df_sample.sort_index(inplace=True)
df_sample

                     email    full_name  first   last
0     john.doe@example.com     john doe   john    doe
1   jane.smith@example.com   jane smith   jane  smith
2  peter.jones@example.com  peter jones  peter  jones
3           tony.doe@e.com     tony doe   tony    doe

In [132]:
df_sample['last'].sort_values()

0      doe
3      doe
2    jones
1    smith
Name: last, dtype: object

In [133]:
df['ConvertedComp'].nlargest(10)

Respondent
58      2000000.0
102     2000000.0
166     2000000.0
436     2000000.0
452     2000000.0
491     2000000.0
539     2000000.0
770     2000000.0
789     2000000.0
1232    2000000.0
Name: ConvertedComp, dtype: float64

In [134]:
df.nlargest(10,'ConvertedComp')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
58,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,NaN,"Developer, back-end;Developer, desktop or ente...",28,19,23,Very satisfied,Very satisfied,Very confident,Yes,No,I am not interested in new job opportunities,1-2 years ago,NaN,Yes,Office environment or company culture;Remote w...,Re-entry into the workforce,USD,United States dollar,113000.0,Weekly,2000000.0,40.0,There's no schedule or spec; I work on what se...,Being tasked with non-development work;Non-wor...,"Less than half the time, but at least one day ...",Home,A little above average,"Yes, because I see value in code review",1.0,"No, but I think we should",Developers and management have nearly equal in...,I have a great deal of influence,C#;Java;SQL,C#;F#;Java;Kotlin;SQL,Microsoft SQL Server;Oracle;SQLite,Microsoft SQL Server;Oracle;SQLite,Android;Windows,Android;Raspberry Pi;Windows,ASP.NET;jQuery,Angular/Angular.js;ASP.NET;jQuery,.NET,Hadoop;.NET;.NET Core;Node.js;Puppet;Xamarin,Android Studio;Visual Studio,Windows,I do not use containers,NaN,NaN,Yes,Yes,Yes,I don't use social media,In real life (in person),Login,I don't remember,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was much faster,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,NaN,47.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,NaN,Easy
102,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...","5,000 to 9,999 employees","Developer, full-stack",8,29,5,Slightly satisfied,Slightly satisfied,Somewhat confident,No,No,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,"Write any code;Write code by hand (e.g., on a ...",Yes,Office environment or company culture;Opportun...,"Something else changed (education, award, medi...",USD,United States dollar,67800.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Distrac...,Less than once per month / Never,Office,Average,No,NaN,"No, but I think we should",Not sure,I have some influence,C#;HTML/CSS;JavaScript;SQL;TypeScript,C;C++;Elixir;Go;Ruby;WebAssembly,Microsoft SQL Server,MongoDB;PostgreSQL;SQLite,Microsoft Azure,AWS;Kubernetes;Microsoft Azure,ASP.NET;jQuery;React.js;Other(s):,Angular/Angular.js;Vue.js,.NET;.NET Core,Node.js,Notepad++;Visual Studio;Visual Studio Code,Windows,I do not use containers,Non-currency applications of blockchain,Useful for immutable record keeping outside of...,No,Yes,Yes,I don't use social media,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,37.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
166,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","A social science (ex. anthropology, psychology...",Participated in a full-time developer training...,20 to 99 employees,"Developer, back-end;Developer, front-end;Devel...",7,15,6,Slightly satisfied,Slightly satisfied,Very confident,No,Not sure,"Iâ€™m not actively looking, but I am open to n...",3-4 years ago,Write any code;Complete a take-home project;So...,No,Financial performance or funding status of the...,I had a negative experience or interaction at ...,USD,United States dollar,137000.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Not enough people...,Less than once per month / Never,Home,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;Go;HTML/CSS;Java;JavaScr...,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redi...,PostgreSQL;Redis;SQLite,AWS;Docker;Linux,AWS;Docker;iOS;Kubernetes;Linux,jQuery;React.js;Ruby on Rails,React.js;Ruby on Rails,NaN,NaN,Vim,Linux-based,Development;Testing;Production,Not at all,A passing fad,Yes,SIGH,Yes,Twitter,Online,Username,2011,A few times per month or weekly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not at all",Just as welcome now as I felt last year,NaN,30.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
436,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,20 to 99 employees,"Database administrator;Developer, back-end;Dev...",20,18,17,Slightly satisfied,Slightly satisfied,Somewhat confident,Yes,I am already a manager,"Iâ€™m not actively looking, but I am open to n...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,"My job status changed (promotion, new job, etc.)",USD,United States dollar,85000.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Meetings;Not e...,A few days each month,Office,Far above average,"Yes, because I see value in code review",NaN,"No, but I think we should","The CTO, CIO, or other management purchase new...",I have some influence,Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...,Bash/Shell/PowerShell;Go;HTML/CSS;JavaScript;P...,Microsoft SQL Server;MySQL;Redis;SQLite,Couchbase;MySQL;Oracle;Redis,Android;AWS;Docker;Google Cloud Platform;Linux...,Android;Arduino;Docker;Google Cloud Platform;L...,jQuery;Laravel;React.js;Vue.js,Laravel;React.js;Vue.js,Node.js,Node.js;React Native;TensorFlow,Android Studio;Atom;Sublime Text;Visual Studio...,Windows,Development;Testing;Production,Not at all,Useful across many domains and could change ma...,Yes,SIGH,Yes,Reddit,Neither,Username,2010,Daily or almost daily,Find answers to specific questions;Contribute ...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,38.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Too long,Easy
452,I am a developer by profession,True,Never,The quality of OSS and closed source software ...,Employed full-time,United States,"Yes, full-time",I never completed any formal education,NaN,Taken an online course in programming or softw...,100 to 499 employees,"Database administrator;Developer, back-end",7,28,7,Very satisfied,Very satisfied,Very confident,No,No,"Iâ€™m not actively looking, but I am open to n...",Less than a year ago,Solve a brain-teaser style puzzle;Interview wi...,No,Specific department or team I'd be working on;...,"Something else changed (education, award, medi...",USD,United States dollar,75000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Meeting...,A few days each month,Home,Average,"Yes, because I see value in code review",5.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,SQL;VBA,Python;SQL,Microsoft SQL Server,MongoDB;Microsoft SQL Server;Oracle;PostgreSQL,Windows,AWS;Linux;Microsoft Azure;Windows,NaN,ASP.NET,.NET,.NET,Notepad++;Visual Studio,Windows,I do not use containers,Not at all,NaN,Yes,"Fortunately, someone else has that title",What?,Facebook,In real life (in person),Screen Name,2013,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,0-10 minutes,Yes,Multiple times per day,Yes,"No, I've heard of them, but I am not part of a...","Yes, definitely",Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,35.0,Man,No,NaN,White or of European descent,No,Appropriate in length,Easy
491,I am a developer by profession,True,Less than once per year,NaN,Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, full-stack;Developer, mobile",4,18,Less than 1 year,Very satisfied,Very satisfied,Very confident,No,Not sure,I am not interested in new job opportunities,Less than a year ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,I was preparing for a job search,USD,United States dollar,160000.0,Weekly,2000000.0,45.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Inadequate access...,Less than once per month / Never,Office,Average,"Yes, because I see value in code review",2.0,"Yes, it's part of our process",Not sure,I have little or no influence,Java;Objective-C,Java;Objective-C;Swift,NaN,NaN,Android;iOS,Android;iOS,NaN,NaN,NaN,React Native;Unity 3D,Android Studio;IntelliJ;Vim;Xcode,MacOS,"Outside of work, for personal projects",NaN,A passing fad,Yes,SIGH,What?,YouTube,In real life (in person),Username,2014,A few times per week,Find answers to specific questions;Learn how t...,1-2 times per week,They were about the same,NaN,No,NaN,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,22.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Neither easy nor difficult
539,I am a developer by profession,False,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,Some college/university study without earning ...,Mathematics or statistics,Taken an online course in programming or softw...,"10,000 or more employees",Data scientist or machine learning specialist;...,22,14,20,Very satisfied,Slightly satisfied,Very confident,Yes,No,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,Write any code;Complete a take-home project;In...,Yes,"Languages, frameworks, and other technologies ...",I was preparing for a job search,USD,United States dollar,140000.0,Weekly,2000000.0,50.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Non-wor...,A few days each month,Office,A little above average,"Yes, because I see value in code review",10.0,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;JavaScript;Python;SQL,Go;JavaScript;Python;TypeScript,PostgreSQL;SQLite,Couchbase;MongoDB;PostgreSQL;Redis;SQLite,AWS;Docker;Linux;MacOS;Slack,AWS;Docker;Google Cloud Platform;Linux;MacOS,Express;Flask;React.js,Flask;React.js,Node.js;Pandas;TensorFlow;Torch/PyTorch,Node.js;Torch/PyTorch,PyCharm;Vim;Visual Studio Code,MacOS,Development;Testing;Production,Not at all,A passing fad,No,Also Yes,Yes,Reddit,In real life (in person),Username,I don't remember,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,0-10 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","No, not really",Just as welcome now as I felt last year,Courses on technologies you're interested in,40.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy
770,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","A humanities discipline (ex. literature, histo...",Taken an online course in programming or softw...,"1,000 to 4,999 employees","Developer, full-stack",5,17,3,Very satisfied,Very satisfied,Somewhat confident,No,Not sure,I am not interested in new job opportunities,1-2 years ago,Interview with people in peer roles;Interview ...,No,Office environment or company culture;Remote w...,"Something else changed (education, award, medi...",USD,United States dollar,68000.0,Weekly,2000000.0,38.0,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Non-wor...,All or almost all the time (I'm full-time remote),Home,Average,"Yes, because I see value in code review",6.0,"Yes, it's part of our process",Developers and management have nearly equal in...,I have little or no influence,Go;HTML/CSS;JavaScript;Python;Ruby;SQL,Go;HTML/CSS;Python;Ruby;TypeScript;WebAssembly,MariaDB;MySQL;SQLite,Elasticsearch;MariaDB;PostgreSQL,AWS;Docker;Linux;Raspberry Pi;Slack,Arduino;AWS;Docker;Linux;Raspberry Pi;Slack,Angular/Angular.js;jQuery;Ruby on Rails,Angular/Angular.js;Django;Ruby on Rails,Node.js,Apache Spark;TensorFlow;Torch/PyTorch,PyCharm;RubyMine;Sublime Text,Linux-based,Development;Testing,Non-currency applications of blockchain,NaN,No,SIGH,Yes,Reddit,Online,Username,2011,Daily or almost daily,Find answers to specific questions;Learn how t...,1-2 times per week,Stack Overflow was slightly faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,Yes,"No, I've heard of them, but I am not part of a...",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,29.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
789,I am a developer by profession,True,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,United States,"Yes, full-time","Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"10,000 or more employees","Developer, back-end;Engineer, site reliability",12,9,6,Slightly dissatisfied,Neither satisfied nor dissatisfied,Not at all confident,Yes,Not sure,"Iâ€™m not actively looking, but I am open to n...",3-4 years ago,"Write any code;Write code by hand (e.g., on a ...",No,Specific department or team I'd be working on;...,I had a negative experience or interaction at ...,USD,United States dollar,180000.0,Monthly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Lack of support from management;Toxic work env...,A few days each month,Office,A little above average,"Yes, because I see value in code review",2.0,"Yes, it's not part of our process but the deve...",Developers and management have nearly equal in...,I have little or no influence,C#;F#;Python,F#;Go;Python;Rust,Elasticsearch;Other(s):,Other(s):,Docker;Microsoft Azure,Docker,ASP.NET,NaN,.NET;.NET Core,.NET Core;TensorFlow,IntelliJ;Notepad++;Visual Studio;Visual Studio...,MacOS,Development;Testing;Production,Non-currency applications of blockchain,An irresponsible use of resources,No,"Fortunately, someone else has that title",Yes,Facebook,Online,Handle,2009,Less than once per month or monthly,Find answers to specific questions,Less than once per week,Stack Overflow was slightly faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...","No, not really",Just as welcome now as I felt last year,Tech articles written by other developers;Cour...,31.0,Woman,No,Bisexual,South Asian,No,Appropriate in length,Neither easy nor difficult
1232,I am a developer by profession,False,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,United States,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,2-9 employees,"Developer, front-end;Developer, game or graphi...",4,15,2,Slightly satisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Sol...",No,Industry that I'd be working in;Specific depar...,"Something else changed (education, award, medi...",USD,United States dollar,800000.0,Weekly,2000000.0,40.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Non-work commitme...,A few days each month,Office,A little below average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have little or no influence,HTML/CSS;JavaScript;SQL,Java;Kotlin;Objective-C;Python;Swift;TypeScrip...,MySQL,MongoDB,NaN,Android;AWS;iOS;MacOS;Windows,React.js,React.js,Node.js;Other(s):,Node.js;Other(s):,Visual Studio Code,MacOS,I do not use containers,Non-currency applications of blockchain,Useful across many domains and could change ma...,Yes,Yes,What?,WeChat å¾®ä¿¡,In real life (in person),Username,2014,A few times per week,Find answers to specific questions,1-2 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers,25.0,Man,No,Straight / Heterosexual,East Asian,No,Appropriate in length,Neither easy nor difficult

In [135]:
#grouping and aggregating
df['ConvertedComp'].median()

57287.0

In [136]:
df.median(numeric_only=True)

Hobbyist             1.0
CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [137]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  2.082200e+04   2.078100e+04  24068.000000  18561.000000  29504.000000
mean   4.805641e+11   1.260354e+05     42.113884      5.135203     30.324193
std    6.930090e+13   2.808980e+05     35.367254      5.696296      9.120631
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.566800e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.000000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4125.000000     99.000000     99.000000

In [138]:
df['ConvertedComp'].count()

np.int64(20781)

In [139]:
df['ConvertedComp'].value_counts()

ConvertedComp
2000000.0    246
1000000.0    194
100000.0     179
150000.0     167
120000.0     167
            ...
89875.0        1
89400.0        1
33588.0        1
16764.0        1
57500.0        1
Name: count, Length: 5249, dtype: int64

In [140]:
df['Hobbyist'].value_counts()

Hobbyist
True     26486
False     6524
Name: count, dtype: int64

In [141]:
round(df['Hobbyist'].value_counts(normalize=True)*100,2)

Hobbyist
True     80.24
False    19.76
Name: proportion, dtype: float64

In [142]:
#group by
df['Country'].value_counts()

Country
United States            7770
India                    3377
Germany                  2187
United Kingdom           2137
Canada                   1289
                         ...
Seychelles                  1
Lesotho                     1
Bahamas                     1
Burkina Faso                1
Saint Kitts and Nevis       1
Name: count, Length: 172, dtype: int64

In [143]:
country_grp=df.groupby(['Country'])

In [144]:
country_grp.get_group('India')

/tmp/ipykernel_4090/421256909.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  country_grp.get_group('India')

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",NaN,"Developer, back-end;Engineer, site reliability",8,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,Bash/Shell/PowerShell;C;C++;Elixir;Erlang;Go;P...,Cassandra;Elasticsearch;MongoDB;MySQL;Oracle;R...,Cassandra;DynamoDB;Elasticsearch;Firebase;Mong...,AWS;Docker;Heroku;Linux;MacOS;Slack,Android;Arduino;AWS;Docker;Google Cloud Platfo...,Express;Flask;React.js;Spring,Django;Express;Flask;React.js;Vue.js,Hadoop;Node.js;Pandas,Ansible;Apache Spark;Chef;Hadoop;Node.js;Panda...,Atom;IntelliJ;IPython / Jupyter;PyCharm;Visual...,Linux-based,Development;Testing;Production;Outside of work...,NaN,Useful across many domains and could change ma...,Yes,SIGH,Yes,YouTube,In real life (in person),Handle,2012,A few times per week,Find answers to specific questions;Learn how t...,Less than once per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, definitely",A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,"10,000 or more employees",Data or business analyst;Data scientist or mac...,12,20,10,Slightly dissatisfied,Slightly dissatisfied,Somewhat confident,Yes,Yes,"Iâ€™m not actively looking, but I am open to n...",3-4 years ago,NaN,No,"Languages, frameworks, and other technologies ...",NaN,INR,Indian rupee,950000.0,Yearly,13293.0,70.0,There's no schedule or spec; I work on what se...,NaN,A few days each month,Home,Far above average,"Yes, because I see value in code review",4.0,"Yes, it's part of our process",NaN,NaN,C#;Go;JavaScript;Python;R;SQL,C#;Go;JavaScript;Kotlin;Python;R;SQL,Elasticsearch;MongoDB;Microsoft SQL Server;MyS...,Elasticsearch;MongoDB;Microsoft SQL Server,Linux;Windows,Android;Linux;Raspberry Pi;Windows,Angular/Angular.js;ASP.NET;Django;Express;Flas...,Angular/Angular.js;ASP.NET;Django;Express;Flas...,.NET;Node.js;Pandas;Torch/PyTorch,.NET;Node.js;TensorFlow;Torch/PyTorch,Android Studio;Eclipse;IPython / Jupyter;Notep...,Windows,NaN,Not at all,Useful for immutable record keeping outside of...,No,Yes,Yes,YouTube,Neither,Screen Name,NaN,Multiple times per day,Find answers to specific questions;Get a sense...,3-5 times per week,They were about the same,NaN,Yes,A few times per month or weekly,Yes,"No, and I don't know what those are","Yes, somewhat",Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,True,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,Student,3,13,NaN,NaN,NaN,NaN,NaN,NaN,"Iâ€™m not actively looking, but I am open to n...",I've never had a job,NaN,NaN,"Industry that I'd be working in;Languages, fra...","Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;Bash/Shell/PowerShell;C;C++;HTML/CSS;...,Assembly;Bash/Shell/PowerShell;C;C++;C#;Go;HTM...,MariaDB;MySQL;Oracle;SQLite,MariaDB;MongoDB;Microsoft SQL Server;MySQL;Ora...,Linux;Windows,Android;Google Cloud Platform;iOS;Linux;MacOS;...,NaN,Angular/Angular.js;ASP.NET;Django;Drupal;jQuer...,NaN,.NET;.NET Core;Node.js;TensorFlow;Unity 3D;Unr...,Atom;NetBeans;Notepad++;Sublime Text;Vim,Linux-based,Development,NaN,NaN,Yes,Yes,What?,YouTube,In real life (in person),NaN,2018,Daily or almost daily,Find answers to specific questions;Learn how t...,More than 10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,Yes,"No, I've heard of them, but I am not part of a...","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,True,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,"10,000 or more employees","Developer, back-end;DevOps specialist",7,15,2,Slightly satisfied,Very satisfied,Very confident,Not sure,Yes,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Int...",No,Specific department or team I'd be working on;...,I was preparing for a job search,INR,Indian rupee,400000.0,Yearly,5597.0,7.0,There is a schedule and/or spec (made by me or...,Meetings;Time spent commuting,Less than once per month / Never,"Other place, such as a coworking space or cafe",Average,No,NaN,"Yes, it's not part of our process but the deve...","The CTO, CIO, or other management purchase new...",I have little or no influence,Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...,HTML/CSS;JavaScript;Python,Elasticsearch;Firebase;MariaDB;MongoDB;MySQL;O...,Firebase;PostgreSQL;Redis;Other(s):,Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Wo...,AWS;Docker;Heroku;Kubernetes;Linux;MacOS;WordP...,Django;Express;Flask;jQuery,Express;Flask;jQuery;React.js;Vue.js,Node.js,Node.js,Notepad++;Visual Studio Code,MacOS,Testing,Not at all,Useful for immutable record keeping outside of...,Yes,Also Yes,What?,YouTube,In real life (in person),Username,2012,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, definitely",Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,True,Never,NaN,Employed full-time,India,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,20 to 99 employees,"Developer, front-end;Developer, mobile",2,17,2,Very satisfied,Very satisfied,Very confident,No,Not sure,"Iâ€™m not actively looking, but I am open to n...",Less than a year ago,Write any code;Solve a brain-teaser style puzz...,No,"Languages, frameworks, and other technologies ...","My job status changed (promotion, new job, etc.)",INR,Indian rupee,NaN,Monthly,NaN,48.0,There's no schedule or spec; I work on what se...,NaN,About half the time,Office,Average,"Yes, because I see value in code review",NaN,"Yes, it's not part of our process but the deve...",Not sure,NaN,Assembly;C;C++;C#;HTML/CSS;Java,Kotlin,Firebase;MySQL;Oracle;SQLite,Firebase;SQLite,Android,Android,ASP.NET,NaN,NaN,NaN,Android Studio;IntelliJ,Linux-based,NaN,NaN,NaN,Yes,Yes,What?,WhatsApp,In real life (in person),NaN,2017,Multiple times per day,Find answers to specific questions,More than 10 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,A few times per week,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33188,I am a developer by profession,True,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,10 to 19 employees,"Designer;Developer, back-end;Developer, deskto...",2,21,2,Very satisfied,Very satisfied,NaN,NaN,NaN,"Iâ€™m not actively looking, but I am open to n...",NA - I am an independent contractor or self em...,Solve a brain-teaser style puzzle;Interview wi...,No,"Languages, frameworks, and other technologies ...",I was preparing for a job search,INR,Indian rupee,50000.0,Monthly,8400.0,45.0,There is a schedule and/or spec (made by me or...,Distracting work environment;Inadequate access...,About half the time,Office,A little above average,"Yes, because I see value in code review",5.0,NaN,NaN,NaN,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...,Bash/Shell/PowerShell;HTML/CSS;JavaScript;Pyth...,Elasticsearch;Microsoft SQL Server;MySQL;Postg...,Cassandra;DynamoDB;Elasticsearch;MongoDB;MySQL...,AWS;Docker;Google Cloud Platform;Heroku;Linux;...,AWS;Docker;Google Cloud Platform;Heroku;Linux;...,Angular/Angular.js;Django;Flask;React.js;Vue.js,Django;React.js,Cordova;Pandas,Ansible;Cordova;Flutter;Hadoop;Node.js;Pandas;...,IPython / Jupyter;Visual Studio;Visual Studio ...,MacOS,Development;Testing;Production;Outside of work...,NaN,A passing fad,Yes,Yes,Yes,WhatsApp,In real life (in person),Login,2013,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,11-30 minutes,Yes,Less than once per month or monthly,Yes,"No, and I don't know what those are","Yes, somewhat",A lot less welcome now than last year,Industry news about technologies you're intere...,24.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Easy
33194,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,20 to 99 employees,"Developer, desktop or enterprise applications",5,19,4,Slightly dissatisfied,Very dissatisfied,Somewhat confident,Yes,Yes,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,"Write code by hand (e.g., on a whiteboard);Sol...",No,Industry that I'd be working in;Office environ...,I was preparing for a job search,INR,Indian rupee,NaN,NaN,NaN,50.0,There's no schedule or spec; I work on what se...,Inadequate access to necessary tools;Not enoug...,Less than once per month / Never,Office,A little below average,"Yes, because I see value in code review",5.0,"No, but I think we should",Developers and management have nearly equal in...,I have little or no influence,HTML/CSS;Java;JavaScript,HTML/CSS;Java;JavaScript;Python,MySQL;PostgreSQL;Redis;SQLite,MySQL,Android;Google Cloud Platform;Windows,Google Cloud Platform;Windows,Angular/Angular.js;Spring,Spring,TensorFlow,TensorFlow,Eclipse;IntelliJ;IPython / Jupyter;Notepad++,Windows,Production,Not at all,NaN,Yes,Yes,Yes,Facebook,Online,Login,2013,Multiple times per day,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was slightly faster,31-60 minutes,Yes,I have never participated in Q&A on Stack Over...,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are",Not sure,Just as welcome now as I felt last year,Courses on technologies you're interested in,NaN,Woman,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
33201,I am a developer by profession,False,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)",I never declared a major,NaN,10 to 19 employees,"Developer, back-end",4,15,4,Very dissatisfied,Very dissatisfied,Not at all confident,No,No,I am actively looking for a job,Less than a year ago,"Write code by hand (e.g., on a whiteboard)",No,NaN,NaN,INR,Indian rupee,NaN,Monthly,NaN,NaN,There's no schedule or spec; I work on what se...,Distracting work environment;Lack of support f...,NaN,"Other place, such as a coworking space or cafe",A little below average,"Yes, because I was told to do so",NaN,"No, and I'm glad we don't",Not sure,I have little or no influence,HTML/CSS;Java;JavaScript,HTML/CSS;Java;JavaScript,SQLite,MariaDB;MongoDB;MySQL;PostgreSQL,NaN,NaN,jQuery,jQuery,Node.js,Node.js,Eclipse;Notepad++;Visual Studio Code,Windows,I do not use containers,Not at all,NaN,Yes,"Fortunately, someone else has that title",Yes,LinkedIn,Neither,Login,NaN,Daily or almost daily,Meet other people with similar skills or inter...,1-2 times per week,Stack Overflow was much faster,60+ minutes,Not sure / can't remember,NaN,"No, I knew that Stack Overflow had a job board...","No, I've heard of them, but I am not part of a...",Not sure,Somewhat less welcome now than last year,NaN,NaN,Man,No,NaN,South Asian,No,Too long,Neither easy nor difficult
33205,I am a developer by profession,True,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Masterâ€™s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,100 to 499 employees,"Developer, back-end;Developer, front-end",8,16,5,Slightly dissatisfied,Neither satisfied nor dissatisfied,NaN,NaN,NaN,"Iâ€™m not actively looking, but I am open to n...",NaN,Interview with people in peer roles,NaN,Remote work options;Flex time or a flexible sc...,"Something else changed (education, award, medi...",INR,Indian rupee,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Distracting work environment;Lack of support f...,Less than once per month / Never,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;C++;HTML/CSS;Java;JavaScript;PHP;SQL,Python;Ruby,Microsoft SQL Server;MySQL;Oracle;SQLite,Cassandra;MongoDB,Android;Heroku;Linux;Windows;WordPress,AWS;Docker,jQuery;Laravel,Ruby on Rails,NaN,NaN,NetBeans;Sublime Text;Visual Studio Code,Linux-based,NaN,Not at all,NaN,NaN,Also Yes,NaN,WhatsApp,In real life (in person),NaN,2015,A few times per month or weekly,Find answers to specific questions;Learn how t...,NaN,Stack Overflow was slightly faster,31-60 minutes,Yes,NaN,NaN,NaN,Neutral,NaN,NaN,NaN,Man,NaN,NaN,NaN,NaN,Too long,Easy
33216,I am a developer by profession,False,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelorâ€™s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,"5,000 to 9,999 employees","Developer, back-end;Developer, desktop or ente...",4,12,4,Slightly satisfied,Slightly satisfied,Somewhat confident,No,Yes,"Iâ€™m not actively looking, but I am open to n...",1-2 years ago,Write any code;Interview with people in senior...,No,Financial performance or funding status of the...,I was preparing for a job search,INR,Indian rupee,NaN,NaN,NaN,NaN,There is a schedule and/or spec (made by me or...,Being tasked with non-development work;Inadequ...,Less than once per month / Never,Office,A little above average,"Yes, because I see value in code review",8.0,"Yes, it's part of our process","The CTO, CIO, or other management purchase new...",I have little or no influence,C#;JavaScript,JavaScript,NaN,NaN,Windows,Android;iOS,Angular/Angular.js,Angular/Angular.js,.NET;.NET Core,.NET;.NET Core,Visual Studio;Visual Studio Code,Windows,I do not use containers,Not at all,NaN,Yes,Yes,Yes,Instagram,In real life (in person),Username,2015,Daily or almost daily,Find answers to specific questions;Learn how t...,6-10 times per week,They were about the same,NaN,Yes,Less than once per month or monthly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in len,NaN

In [145]:
filt = df['Country' ] == 'India'
df.loc[filt] ['SocialMedia' ].value_counts()

SocialMedia
WhatsApp                    1135
YouTube                      697
LinkedIn                     340
Facebook                     335
Instagram                    293
Twitter                      193
Reddit                       171
I don't use social media      98
Snapchat                       8
Hello                          2
VK Ð’ÐšÐ¾Ð½Ñ‚Ð°ÌÐºÑ‚Ðµ        2
Weibo æ–°æµªå¾®åš             1
WeChat å¾®ä¿¡                  1
Name: count, dtype: int64

In [146]:
df.groupby(['Country'])['SocialMedia'].value_counts()

Country      SocialMedia
Afghanistan  Facebook                    5
             I don't use social media    2
             YouTube                     2
             Instagram                   1
Albania      Facebook                    8
                                        ..
Zambia       WhatsApp                    1
Zimbabwe     WhatsApp                    9
             Twitter                     7
             Facebook                    2
             Instagram                   2
Name: count, Length: 1007, dtype: int64

In [147]:
df.groupby(['Country'])['SocialMedia'].value_counts().loc['India'] #or country_grp['SocialMedia'].value_counts().loc['India']

SocialMedia
WhatsApp                    1135
YouTube                      697
LinkedIn                     340
Facebook                     335
Instagram                    293
Twitter                      193
Reddit                       171
I don't use social media      98
Snapchat                       8
Hello                          2
VK Ð’ÐšÐ¾Ð½Ñ‚Ð°ÌÐºÑ‚Ðµ        2
WeChat å¾®ä¿¡                  1
Weibo æ–°æµªå¾®åš             1
Name: count, dtype: int64

In [148]:
country_grp['ConvertedComp'].median()

Country
Afghanistan                              1596.0
Albania                                 11040.0
Algeria                                  6096.0
Andorra                                     NaN
Angola                                   7764.0
                                         ...
Venezuela, Bolivarian Republic of...     9600.0
Viet Nam                                 8280.0
Yemen                                   13854.0
Zambia                                  12607.0
Zimbabwe                                18600.0
Name: ConvertedComp, Length: 172, dtype: float64

In [149]:
country_grp['ConvertedComp'].agg(['mean','median'])

                                              mean   median
Country
Afghanistan                            4150.285714   1596.0
Albania                               26139.789474  11040.0
Algeria                                7739.866667   6096.0
Andorra                                        NaN      NaN
Angola                                 7764.000000   7764.0
...                                            ...      ...
Venezuela, Bolivarian Republic of...  22623.368421   9600.0
Viet Nam                              17784.620690   8280.0
Yemen                                 13854.000000  13854.0
Zambia                                10254.333333  12607.0
Zimbabwe                              20500.000000  18600.0

[172 rows x 2 columns]

In [150]:
filt = df['Country' ] == 'India'
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

1151

In [151]:
# error country_grp['LanguageWorkedWith'].str.contains('Python').sum()==>we use apply

In [152]:
country_grp['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())

Country
Afghanistan                              2
Albania                                  9
Algeria                                  9
Andorra                                  0
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    13
Viet Nam                                29
Yemen                                    1
Zambia                                   1
Zimbabwe                                10
Name: LanguageWorkedWith, Length: 172, dtype: int64

In [153]:
country_respondents=df['Country'].value_counts()
country_respondents

Country
United States            7770
India                    3377
Germany                  2187
United Kingdom           2137
Canada                   1289
                         ...
Seychelles                  1
Lesotho                     1
Bahamas                     1
Burkina Faso                1
Saint Kitts and Nevis       1
Name: count, Length: 172, dtype: int64

In [154]:
country_uses_python=country_grp['LanguageWorkedWith'].apply(lambda x:x.str.contains('Python').sum())
country_uses_python

Country
Afghanistan                              2
Albania                                  9
Algeria                                  9
Andorra                                  0
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    13
Viet Nam                                29
Yemen                                    1
Zambia                                   1
Zimbabwe                                10
Name: LanguageWorkedWith, Length: 172, dtype: int64

In [155]:
python_df=pd.concat([country_respondents,country_uses_python],axis='columns',sort=False)
python_df

                       count  LanguageWorkedWith
Country
United States           7770                3739
India                   3377                1151
Germany                 2187                 938
United Kingdom          2137                 894
Canada                  1289                 603
...                      ...                 ...
Seychelles                 1                   0
Lesotho                    1                   0
Bahamas                    1                   1
Burkina Faso               1                   0
Saint Kitts and Nevis      1                   0

[172 rows x 2 columns]

In [156]:
python_df.rename(columns={'count':'NumRespondents','LanguageWorkedWith':'NumKnowsPython'},inplace=True)
python_df

                       NumRespondents  NumKnowsPython
Country
United States                    7770            3739
India                            3377            1151
Germany                          2187             938
United Kingdom                   2137             894
Canada                           1289             603
...                               ...             ...
Seychelles                          1               0
Lesotho                             1               0
Bahamas                             1               1
Burkina Faso                        1               0
Saint Kitts and Nevis               1               0

[172 rows x 2 columns]

In [157]:
python_df['pctKnowsPython']=(python_df['NumKnowsPython']/python_df['NumRespondents'])*100
python_df

                       NumRespondents  NumKnowsPython  pctKnowsPython
Country
United States                    7770            3739       48.120978
India                            3377            1151       34.083506
Germany                          2187             938       42.889803
United Kingdom                   2137             894       41.834347
Canada                           1289             603       46.780450
...                               ...             ...             ...
Seychelles                          1               0        0.000000
Lesotho                             1               0        0.000000
Bahamas                             1               1      100.000000
Burkina Faso                        1               0        0.000000
Saint Kitts and Nevis               1               0        0.000000

[172 rows x 3 columns]

In [158]:
python_df.sort_values(by='pctKnowsPython',ascending=False,inplace=True)
python_df

                       NumRespondents  NumKnowsPython  pctKnowsPython
Country
Bahamas                             1               1           100.0
Mali                                1               1           100.0
Oman                                3               3           100.0
Guinea                              1               1           100.0
Angola                              1               1           100.0
...                               ...             ...             ...
Mozambique                          1               0             0.0
Seychelles                          1               0             0.0
Lesotho                             1               0             0.0
Burkina Faso                        1               0             0.0
Saint Kitts and Nevis               1               0             0.0

[172 rows x 3 columns]

In [159]:
python_df.loc['Japan']

NumRespondents    148.000000
NumKnowsPython     69.000000
pctKnowsPython     46.621622
Name: Japan, dtype: float64

In [160]:
#df.groupby(['col1','col2'],dropna=False)['col3','col4'].sum().reset_index(name='new_col')
#df.groupby(['col1','col2'])['col3'].agg(['sum','mean'])
'''
df.groupby(['col1','col2']).agg(
    new_col1=('col3', 'sum'),
    new_col2=('col4', 'mean')
)
'''

"\ndf.groupby(['col1','col2']).agg(\n    new_col1=('col3', 'sum'),\n    new_col2=('col4', 'mean')\n)\n"

In [161]:
#joins

In [162]:
df1 = pd.DataFrame({
"city": ["new york","chicago","orlando"],
"temperature": [21,14,35]
})
df2 = pd.DataFrame({
"city": ["new york","chicago","san francisco"],
"humidity": [65,68,75]
})
print(df1)
print(df2)

       city  temperature
0  new york           21
1   chicago           14
2   orlando           35
            city  humidity
0       new york        65
1        chicago        68
2  san francisco        75

In [163]:
df3=pd.merge(df1,df2,on='city') #inner join
df3

       city  temperature  humidity
0  new york           21        65
1   chicago           14        68

In [164]:
df3=pd.merge(df1,df2,on='city',how='outer') #union
df3

            city  temperature  humidity
0        chicago         14.0      68.0
1       new york         21.0      65.0
2        orlando         35.0       NaN
3  san francisco          NaN      75.0

In [165]:
df3=pd.merge(df1,df2,on='city',how='left') #left join
df3

       city  temperature  humidity
0  new york           21      65.0
1   chicago           14      68.0
2   orlando           35       NaN

In [166]:
df3=pd.merge(df1,df2,on='city',how='right') #right join
df3

            city  temperature  humidity
0       new york         21.0        65
1        chicago         14.0        68
2  san francisco          NaN        75

In [167]:
df3=pd.merge(df1,df1,on='city') #self join
df3

       city  temperature_x  temperature_y
0  new york             21             21
1   chicago             14             14
2   orlando             35             35

In [168]:
df3=pd.merge(df1,df2,how='cross') #cross join
df3

     city_x  temperature         city_y  humidity
0  new york           21       new york        65
1  new york           21        chicago        68
2  new york           21  san francisco        75
3   chicago           14       new york        65
4   chicago           14        chicago        68
5   chicago           14  san francisco        75
6   orlando           35       new york        65
7   orlando           35        chicago        68
8   orlando           35  san francisco        75

In [169]:
df3=pd.merge(df1,df2,on='city',how='outer',indicator=True) #union
df3

            city  temperature  humidity      _merge
0        chicago         14.0      68.0        both
1       new york         21.0      65.0        both
2        orlando         35.0       NaN   left_only
3  san francisco          NaN      75.0  right_only

In [170]:
df1 = pd.DataFrame({
"city": ["new york","chicago","orlando", "baltimore"],
"temperature": [21,14,35,38],
"humidity": [65,68,71, 75]
})
df1

        city  temperature  humidity
0   new york           21        65
1    chicago           14        68
2    orlando           35        71
3  baltimore           38        75

In [171]:
df2 = pd.DataFrame({
"city": ["chicago","new york","san diego"],
"temperature": [21,14,35],
"humidity": [65,68,71]
})
df2

        city  temperature  humidity
0    chicago           21        65
1   new york           14        68
2  san diego           35        71

In [172]:
df3=pd.merge(df1,df2,on='city')
df3

       city  temperature_x  humidity_x  temperature_y  humidity_y
0  new york             21          65             14          68
1   chicago             14          68             21          65

In [173]:
df3=pd.merge(df1,df2,on='city',suffixes=('_first','_second'))
df3

,city,temperature_first,humidity_first,temperature_second,humidity_second
0,new york,21,65,14,68
1,chicago,14,68,21,65

In [174]:
#pd.merge(df1,df2,on=['col1','col2'])
#pd.merge(df1,df2,left_on='col1',right_on='col1')
#pd.merge(df1,df2,left_on=['col1','col2'],right_on=['col1','col2'])

In [175]:
#pivot
data = {
    "date": [
        "5/1/2017", "5/2/2017", "5/3/2017",
        "5/1/2017", "5/2/2017", "5/3/2017",
        "5/1/2017", "5/2/2017", "5/3/2017"
    ],
    "city": [
        "new york", "new york", "new york",
        "mumbai", "mumbai", "mumbai",
        "beijing", "beijing", "beijing"
    ],
    "temperature": [65, 66, 68, 75, 78, 82, 80, 77, 79],
    "humidity": [56, 58, 60, 80, 83, 85, 26, 30, 35]
}

df1 = pd.DataFrame(data)
df1

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [176]:
df1.pivot(index='date',columns='city')

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [177]:
df1.pivot(index='date',columns='city',values='humidity')

city      beijing  mumbai  new york
date
5/1/2017       26      80        56
5/2/2017       30      83        58
5/3/2017       35      85        60

In [178]:
data = {
    "date": [
        "5/1/2017", "5/1/2017",
        "5/2/2017", "5/2/2017",
        "5/1/2017", "5/1/2017",
        "5/2/2017", "5/2/2017"
    ],
    "city": [
        "new york", "new york",
        "new york", "new york",
        "mumbai", "mumbai",
        "mumbai", "mumbai"
    ],
    "temperature": [65, 61, 70, 72, 75, 78, 82, 80],
    "humidity": [56, 54, 60, 62, 80, 83, 85, 26]
}

df1 = pd.DataFrame(data)
df1

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/1/2017  new york           61        54
2  5/2/2017  new york           70        60
3  5/2/2017  new york           72        62
4  5/1/2017    mumbai           75        80
5  5/1/2017    mumbai           78        83
6  5/2/2017    mumbai           82        85
7  5/2/2017    mumbai           80        26

In [179]:
#pivot table allows to summerize and agreggate your tabular data
df1.pivot_table(index='city',columns='date')

         humidity          temperature
date     5/1/2017 5/2/2017    5/1/2017 5/2/2017
city
mumbai       81.5     55.5        76.5     81.0
new york     55.0     61.0        63.0     71.0

In [180]:
df1.pivot_table(index='city',columns='date',aggfunc='sum',margins=True) #bydefault mean

         humidity               temperature
date     5/1/2017 5/2/2017  All    5/1/2017 5/2/2017  All
city
mumbai        163      111  274         153      162  315
new york      110      122  232         126      142  268
All           273      233  506         279      304  583

In [181]:
data = {
    "date": [
        "2017-05-01",
        "2017-05-02",
        "2017-05-03",
        "2017-12-01",
        "2017-12-02",
        "2017-12-03"
    ],
    "city": [
        "new york",
        "new york",
        "new york",
        "new york",
        "new york",
        "new york"
    ],
    "temperature": [65, 61, 70, 30, 28, 25],
    "humidity": [56, 54, 60, 50, 52, 51]
}

df1 = pd.DataFrame(data)
df1["date"] = pd.to_datetime(df1["date"])
df1

        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

In [182]:
df1.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

/tmp/ipykernel_4090/1406934752.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df1.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667

In [183]:
import numpy as np

In [184]:
#cleaning data
df = pd.DataFrame({
    'first': ['Corey', 'Jane', 'John', 'Chris', np.nan, None, 'NA'],
    'last': ['Schafer', 'Doe', 'Doe', 'Schafer', np.nan, np.nan, 'Missing'],
    'email': [
        'CoreyMSchafer@gmail.com',
        'JaneDoe@email.com',
        'JohnDoe@email.com',
        None,
        np.nan,
        'Anonymous@email.com',
        'NA'
    ],
    'age': ['33', '55', '63','36', None, None, 'Missing']
})
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [185]:
df.dropna()

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
6     NA  Missing                       NA  Missing

In [186]:
#default-- df.dropna(axis='index', how='any') any---when any value missing in the row,,
#all---when all value are missing in the row

In [187]:
df.dropna(axis='index', how='all')

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [188]:
#if i want to drop rows if some specific col have missing value
#df.dropna(axis='index', how='any', subset=['email'])

In [189]:
df.dropna(axis='index', how='any', subset=['email'])

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [190]:
df.dropna(axis='index', how='all', subset=['email','last']) #use inplace for permanent

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [191]:
df

   first     last                    email      age
0  Corey  Schafer  CoreyMSchafer@gmail.com       33
1   Jane      Doe        JaneDoe@email.com       55
2   John      Doe        JohnDoe@email.com       63
3  Chris  Schafer                     None       36
4    NaN      NaN                      NaN     None
5   None      NaN      Anonymous@email.com     None
6     NA  Missing                       NA  Missing

In [192]:
df.replace({'NA':np.nan,'Missing':np.nan},inplace=True)
df

   first     last                    email   age
0  Corey  Schafer  CoreyMSchafer@gmail.com    33
1   Jane      Doe        JaneDoe@email.com    55
2   John      Doe        JohnDoe@email.com    63
3  Chris  Schafer                     None    36
4    NaN      NaN                      NaN  None
5   None      NaN      Anonymous@email.com  None
6    NaN      NaN                      NaN   NaN

In [193]:
df.dropna()

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63

In [194]:
df.isna()

   first   last  email    age
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False   True  False
4   True   True   True   True
5   True   True  False   True
6   True   True   True   True

In [195]:
df.fillna(0)

   first     last                    email age
0  Corey  Schafer  CoreyMSchafer@gmail.com  33
1   Jane      Doe        JaneDoe@email.com  55
2   John      Doe        JohnDoe@email.com  63
3  Chris  Schafer                        0  36
4      0        0                        0   0
5      0        0      Anonymous@email.com   0
6      0        0                        0   0

In [196]:
df.dtypes

first    object
last     object
email    object
age      object
dtype: object

In [197]:
df['age']=df['age'].astype(float)

In [198]:
df.dtypes

first     object
last      object
email     object
age      float64
dtype: object

In [199]:
df['age'].mean()

np.float64(46.75)

In [200]:
na_vals=['NA','Missing']
df=pd.read_csv('/content/data.csv',index_col='Respondent',na_values=na_vals)

In [201]:
df.head(2)

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,OrgSize,DevType,YearsCode,Age1stCode,YearsCodePro,CareerSat,JobSat,MgrIdiot,MgrMoney,MgrWant,JobSeek,LastHireDate,LastInt,FizzBuzz,JobFactors,ResumeUpdate,CurrencySymbol,CurrencyDesc,CompTotal,CompFreq,ConvertedComp,WorkWeekHrs,WorkPlan,WorkChallenge,WorkRemote,WorkLoc,ImpSyn,CodeRev,CodeRevHrs,UnitTests,PurchaseHow,PurchaseWhat,LanguageWorkedWith,LanguageDesireNextYear,DatabaseWorkedWith,DatabaseDesireNextYear,PlatformWorkedWith,PlatformDesireNextYear,WebFrameWorkedWith,WebFrameDesireNextYear,MiscTechWorkedWith,MiscTechDesireNextYear,DevEnviron,OpSys,Containers,BlockchainOrg,BlockchainIs,BetterLife,ITperson,OffOn,SocialMedia,Extraversion,ScreenName,SOVisit1st,SOVisitFreq,SOVisitTo,SOFindAnswer,SOTimeSaved,SOHowMuchTime,SOAccount,SOPartFreq,SOJobs,EntTeams,SOComm,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",NaN,NaN,4,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HTML/CSS;Java;JavaScript;Python,C;C++;C#;Go;HTML/CSS;Java;JavaScript;Python;SQL,SQLite,MySQL,MacOS;Windows,Android;Arduino;Windows,Django;Flask,Flask;jQuery,Node.js,Node.js,IntelliJ;Notepad++;PyCharm,Windows,I do not use containers,NaN,NaN,Yes,"Fortunately, someone else has that title",Yes,Twitter,Online,Username,2017,A few times per month or weekly,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,31-60 minutes,No,NaN,"No, I didn't know that Stack Overflow had a jo...","No, and I don't know what those are",Neutral,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,NaN,"Developer, desktop or enterprise applications;...",NaN,17,NaN,NaN,NaN,NaN,NaN,NaN,I am actively looking for a job,I've never had a job,NaN,NaN,Financial performance or funding status of the...,"Something else changed (education, award, medi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C++;HTML/CSS;Python,C++;HTML/CSS;JavaScript;SQL,NaN,MySQL,Windows,Windows,Django,Django,NaN,NaN,Atom;PyCharm,Windows,I do not use containers,NaN,Useful across many domains and could change ma...,Yes,Yes,Yes,Instagram,Online,Username,2017,Daily or almost daily,Find answers to specific questions;Learn how t...,3-5 times per week,Stack Overflow was much faster,11-30 minutes,Yes,A few times per month or weekly,"No, I knew that Stack Overflow had a job board...","No, and I don't know what those are","Yes, somewhat",Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult

In [202]:
df['YearsCode'].value_counts(dropna=False)

YearsCode
5                     2634
10                    2490
6                     2355
4                     2101
7                     2027
8                     2000
3                     1920
2                     1473
15                    1469
20                    1367
12                    1298
9                     1272
11                     804
14                     797
18                     753
13                     710
1                      701
25                     617
16                     598
30                     584
Less than 1 year       494
17                     487
22                     391
19                     387
35                     312
NaN                    284
23                     281
24                     276
21                     228
40                     184
26                     165
28                     164
27                     155
32                     151
33                     136
37                     133
38                     129
34                     128
36                      98
29                      75
31                      67
39                      60
More than 50 years      48
45                      44
42                      34
43                      25
41                      25
50                      21
44                      15
48                      12
47                      11
49                      11
46                       9
Name: count, dtype: int64

In [203]:
df['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 'Less than 1 year', '30', '9', '26', '40', '19',
       '15', '20', '28', '25', '1', '22', '11', '33', '50', '41', '18',
       '34', '24', '23', '42', '27', '21', '36', '32', '39', '38', '31',
       '37', 'More than 50 years', '29', '44', '45', '48', '46', '43',
       '47', '49'], dtype=object)

In [204]:
df['YearsCode'].replace({'Less than 1 year':0},inplace=True)
df['YearsCode'].replace({'More than 50 years':51},inplace=True)

/tmp/ipykernel_4090/903361970.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['YearsCode'].replace({'Less than 1 year':0},inplace=True)

In [205]:
df['YearsCode'].unique()

array(['4', nan, '3', '16', '13', '6', '8', '12', '2', '5', '17', '10',
       '14', '35', '7', 0, '30', '9', '26', '40', '19', '15', '20', '28',
       '25', '1', '22', '11', '33', '50', '41', '18', '34', '24', '23',
       '42', '27', '21', '36', '32', '39', '38', '31', '37', 51, '29',
       '44', '45', '48', '46', '43', '47', '49'], dtype=object)

In [206]:
df['YearsCode']=df['YearsCode'].astype(float)

In [207]:
df['YearsCode'].mean()

np.float64(11.632371814459452)

In [208]:
df['YearsCode'].median()

9.0

In [209]:
df['YearsCode']=df['YearsCode'].fillna(df['YearsCode'].median())

In [210]:
df['YearsCode'].unique()

array([ 4.,  9.,  3., 16., 13.,  6.,  8., 12.,  2.,  5., 17., 10., 14.,
       35.,  7.,  0., 30., 26., 40., 19., 15., 20., 28., 25.,  1., 22.,
       11., 33., 50., 41., 18., 34., 24., 23., 42., 27., 21., 36., 32.,
       39., 38., 31., 37., 51., 29., 44., 45., 48., 46., 43., 47., 49.])

In [211]:
df['YearsCode']=df['YearsCode'].ffill() #Forward fill (ffill) copies the previous available value.

In [212]:
df['YearsCode']=df['YearsCode'].bfill() #Backward fill (bfill) copies the next available value.

In [213]:
#Handling duplicate values

In [214]:
df = pd.DataFrame({
    'Name': ['Amit', 'Riya', 'Amit', 'Neha', 'Riya'],
    'Age': [22, 23, 22, 24, 23],
    'City': ['Delhi', 'Mumbai', 'Delhi', 'Pune', 'Mumbai']
})
df

   Name  Age    City
0  Amit   22   Delhi
1  Riya   23  Mumbai
2  Amit   22   Delhi
3  Neha   24    Pune
4  Riya   23  Mumbai

In [215]:
df.duplicated() #Detect duplicate rows

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [216]:
df[df.duplicated()]

   Name  Age    City
2  Amit   22   Delhi
4  Riya   23  Mumbai

In [217]:
df[df.duplicated(keep=False)] #all occurence

   Name  Age    City
0  Amit   22   Delhi
1  Riya   23  Mumbai
2  Amit   22   Delhi
4  Riya   23  Mumbai

In [218]:
df.drop_duplicates() #Keeps the first occurrence and removes subsequent duplicates.

   Name  Age    City
0  Amit   22   Delhi
1  Riya   23  Mumbai
3  Neha   24    Pune

In [219]:
df.drop_duplicates(keep='last') #Keep the last occurrence

   Name  Age    City
2  Amit   22   Delhi
3  Neha   24    Pune
4  Riya   23  Mumbai

In [220]:
df.drop_duplicates(keep=False) #Remove every occurrence

   Name  Age  City
3  Neha   24  Pune

In [221]:
#Find duplicates based on selected columns
df.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [222]:
df.drop_duplicates(subset=['Name'])

   Name  Age    City
0  Amit   22   Delhi
1  Riya   23  Mumbai
3  Neha   24    Pune

#windows function

In [223]:
'''
# ROW_NUMBER
df.groupby('group')['col'].cumcount() + 1

# RANK
df.groupby('group')['col'].rank(method='min')

# DENSE_RANK
df.groupby('group')['col'].rank(method='dense')

# SUM OVER PARTITION BY
df.groupby('group')['col'].transform('sum')

# AVG OVER PARTITION BY
df.groupby('group')['col'].transform('mean')

# COUNT(*) OVER PARTITION BY
df.groupby('group')['col'].transform('size')

# LAG
df.groupby('group')['col'].shift(1)

# LEAD
df.groupby('group')['col'].shift(-1)

# Running total
df.groupby('group')['col'].cumsum()

#Running avg
df.groupby('department')['salary'].expanding().mean().reset_index(level=0, drop=True)
'''

"\n# ROW_NUMBER\ndf.groupby('group')['col'].cumcount() + 1\n\n# RANK\ndf.groupby('group')['col'].rank(method='min')\n\n# DENSE_RANK\ndf.groupby('group')['col'].rank(method='dense')\n\n# SUM OVER PARTITION BY\ndf.groupby('group')['col'].transform('sum')\n\n# AVG OVER PARTITION BY\ndf.groupby('group')['col'].transform('mean')\n\n# COUNT(*) OVER PARTITION BY\ndf.groupby('group')['col'].transform('size')\n\n# LAG\ndf.groupby('group')['col'].shift(1)\n\n# LEAD\ndf.groupby('group')['col'].shift(-1)\n\n# Running total\ndf.groupby('group')['col'].cumsum()\n\n#Running avg\ndf.groupby('department')['salary'].expanding().mean().reset_index(level=0, drop=True)\n"

In [224]:
import pandas as pd

data = {
    'employee_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],
    'employee': ['Aman', 'Priya', 'Rahul', 'Neha', 'Aman',
                 'Priya', 'Rahul', 'Neha', 'Aman', 'Priya',
                 'Rahul', 'Neha', 'Aman', 'Priya', 'Rahul'],
    'department': ['IT', 'HR', 'IT', 'HR', 'IT',
                   'HR', 'IT', 'HR', 'IT', 'HR',
                   'IT', 'HR', 'IT', 'HR', 'IT'],
    'date': ['2025-01-03', '2025-01-01', '2025-01-02',
             '2025-01-04', '2025-01-01', '2025-01-03',
             '2025-01-01', '2025-01-02', '2025-01-04',
             '2025-01-02', '2025-01-03', '2025-01-01',
             '2025-01-02', '2025-01-04', '2025-01-05'],
    'salary': [60000, 50000, 60000, 45000, 60000,
               55000, 50000, 45000, 70000, 50000,
               60000, 50000, 65000, 60000, 70000],
    'sales': [3000, 2000, 4000, 1500, 2500,
              3000, 3500, 2000, 5000, 2500,
              4500, 1800, 4000, 3500, 6000]
}

df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])

print(df)

    employee_id employee department       date  salary  sales
0           101     Aman         IT 2025-01-03   60000   3000
1           102    Priya         HR 2025-01-01   50000   2000
2           103    Rahul         IT 2025-01-02   60000   4000
3           104     Neha         HR 2025-01-04   45000   1500
4           105     Aman         IT 2025-01-01   60000   2500
5           106    Priya         HR 2025-01-03   55000   3000
6           107    Rahul         IT 2025-01-01   50000   3500
7           108     Neha         HR 2025-01-02   45000   2000
8           109     Aman         IT 2025-01-04   70000   5000
9           110    Priya         HR 2025-01-02   50000   2500
10          111    Rahul         IT 2025-01-03   60000   4500
11          112     Neha         HR 2025-01-01   50000   1800
12          113     Aman         IT 2025-01-02   65000   4000
13          114    Priya         HR 2025-01-04   60000   3500
14          115    Rahul         IT 2025-01-05   70000   6000

In [225]:
df.sort_values(by=['department','salary'],ascending=[True,False],inplace=True)

In [226]:
df

    employee_id employee department       date  salary  sales
13          114    Priya         HR 2025-01-04   60000   3500
5           106    Priya         HR 2025-01-03   55000   3000
1           102    Priya         HR 2025-01-01   50000   2000
9           110    Priya         HR 2025-01-02   50000   2500
11          112     Neha         HR 2025-01-01   50000   1800
3           104     Neha         HR 2025-01-04   45000   1500
7           108     Neha         HR 2025-01-02   45000   2000
8           109     Aman         IT 2025-01-04   70000   5000
14          115    Rahul         IT 2025-01-05   70000   6000
12          113     Aman         IT 2025-01-02   65000   4000
0           101     Aman         IT 2025-01-03   60000   3000
2           103    Rahul         IT 2025-01-02   60000   4000
4           105     Aman         IT 2025-01-01   60000   2500
10          111    Rahul         IT 2025-01-03   60000   4500
6           107    Rahul         IT 2025-01-01   50000   3500

In [227]:
df['row_num']=df.groupby(['department'])['salary'].cumcount()+1
df

    employee_id employee department       date  salary  sales  row_num
13          114    Priya         HR 2025-01-04   60000   3500        1
5           106    Priya         HR 2025-01-03   55000   3000        2
1           102    Priya         HR 2025-01-01   50000   2000        3
9           110    Priya         HR 2025-01-02   50000   2500        4
11          112     Neha         HR 2025-01-01   50000   1800        5
3           104     Neha         HR 2025-01-04   45000   1500        6
7           108     Neha         HR 2025-01-02   45000   2000        7
8           109     Aman         IT 2025-01-04   70000   5000        1
14          115    Rahul         IT 2025-01-05   70000   6000        2
12          113     Aman         IT 2025-01-02   65000   4000        3
0           101     Aman         IT 2025-01-03   60000   3000        4
2           103    Rahul         IT 2025-01-02   60000   4000        5
4           105     Aman         IT 2025-01-01   60000   2500        6
10          111    Rahul         IT 2025-01-03   60000   4500        7
6           107    Rahul         IT 2025-01-01   50000   3500        8

In [228]:
df['rank']=df.groupby('department')['salary'].rank(method='min',ascending=False)
df

    employee_id employee department       date  salary  sales  row_num  rank
13          114    Priya         HR 2025-01-04   60000   3500        1   1.0
5           106    Priya         HR 2025-01-03   55000   3000        2   2.0
1           102    Priya         HR 2025-01-01   50000   2000        3   3.0
9           110    Priya         HR 2025-01-02   50000   2500        4   3.0
11          112     Neha         HR 2025-01-01   50000   1800        5   3.0
3           104     Neha         HR 2025-01-04   45000   1500        6   6.0
7           108     Neha         HR 2025-01-02   45000   2000        7   6.0
8           109     Aman         IT 2025-01-04   70000   5000        1   1.0
14          115    Rahul         IT 2025-01-05   70000   6000        2   1.0
12          113     Aman         IT 2025-01-02   65000   4000        3   3.0
0           101     Aman         IT 2025-01-03   60000   3000        4   4.0
2           103    Rahul         IT 2025-01-02   60000   4000        5   4.0
4           105     Aman         IT 2025-01-01   60000   2500        6   4.0
10          111    Rahul         IT 2025-01-03   60000   4500        7   4.0
6           107    Rahul         IT 2025-01-01   50000   3500        8   8.0

In [229]:
df['dense_rk']=df.groupby('department')['salary'].rank(method='dense',ascending=False)
df

,employee_id,employee,department,date,salary,sales,row_num,rank,dense_rk
13,114,Priya,HR,2025-01-04,60000,3500,1,1.0,1.0
5,106,Priya,HR,2025-01-03,55000,3000,2,2.0,2.0
1,102,Priya,HR,2025-01-01,50000,2000,3,3.0,3.0
9,110,Priya,HR,2025-01-02,50000,2500,4,3.0,3.0
11,112,Neha,HR,2025-01-01,50000,1800,5,3.0,3.0
3,104,Neha,HR,2025-01-04,45000,1500,6,6.0,4.0
7,108,Neha,HR,2025-01-02,45000,2000,7,6.0,4.0
8,109,Aman,IT,2025-01-04,70000,5000,1,1.0,1.0
14,115,Rahul,IT,2025-01-05,70000,6000,2,1.0,1.0
12,113,Aman,IT,2025-01-02,65000,4000,3,3.0,2.0
0,101,Aman,IT,2025-01-03,60000,3000,4,4.0,3.0
2,103,Rahul,IT,2025-01-02,60000,4000,5,4.0,3.0
4,105,Aman,IT,2025-01-01,60000,2500,6,4.0,3.0
10,111,Rahul,IT,2025-01-03,60000,4500,7,4.0,3.0
6,107,Rahul,IT,2025-01-01,50000,3500,8,8.0,4.0

In [230]:
df['salary_sum']=df.groupby('department')['salary'].transform('sum')
df

,employee_id,employee,department,date,salary,sales,row_num,rank,dense_rk,salary_sum
13,114,Priya,HR,2025-01-04,60000,3500,1,1.0,1.0,355000
5,106,Priya,HR,2025-01-03,55000,3000,2,2.0,2.0,355000
1,102,Priya,HR,2025-01-01,50000,2000,3,3.0,3.0,355000
9,110,Priya,HR,2025-01-02,50000,2500,4,3.0,3.0,355000
11,112,Neha,HR,2025-01-01,50000,1800,5,3.0,3.0,355000
3,104,Neha,HR,2025-01-04,45000,1500,6,6.0,4.0,355000
7,108,Neha,HR,2025-01-02,45000,2000,7,6.0,4.0,355000
8,109,Aman,IT,2025-01-04,70000,5000,1,1.0,1.0,495000
14,115,Rahul,IT,2025-01-05,70000,6000,2,1.0,1.0,495000
12,113,Aman,IT,2025-01-02,65000,4000,3,3.0,2.0,495000
0,101,Aman,IT,2025-01-03,60000,3000,4,4.0,3.0,495000
2,103,Rahul,IT,2025-01-02,60000,4000,5,4.0,3.0,495000
4,105,Aman,IT,2025-01-01,60000,2500,6,4.0,3.0,495000
10,111,Rahul,IT,2025-01-03,60000,4500,7,4.0,3.0,495000
6,107,Rahul,IT,2025-01-01,50000,3500,8,8.0,4.0,495000

In [231]:
df['avg_salary'] = df.groupby('department')['salary'].transform('mean')
df['emp_count'] = df.groupby('department')['employee_id'].transform('size')
df

,employee_id,employee,department,date,salary,sales,row_num,rank,dense_rk,salary_sum,avg_salary,emp_count
13,114,Priya,HR,2025-01-04,60000,3500,1,1.0,1.0,355000,50714.285714,7
5,106,Priya,HR,2025-01-03,55000,3000,2,2.0,2.0,355000,50714.285714,7
1,102,Priya,HR,2025-01-01,50000,2000,3,3.0,3.0,355000,50714.285714,7
9,110,Priya,HR,2025-01-02,50000,2500,4,3.0,3.0,355000,50714.285714,7
11,112,Neha,HR,2025-01-01,50000,1800,5,3.0,3.0,355000,50714.285714,7
3,104,Neha,HR,2025-01-04,45000,1500,6,6.0,4.0,355000,50714.285714,7
7,108,Neha,HR,2025-01-02,45000,2000,7,6.0,4.0,355000,50714.285714,7
8,109,Aman,IT,2025-01-04,70000,5000,1,1.0,1.0,495000,61875.000000,8
14,115,Rahul,IT,2025-01-05,70000,6000,2,1.0,1.0,495000,61875.000000,8
12,113,Aman,IT,2025-01-02,65000,4000,3,3.0,2.0,495000,61875.000000,8
0,101,Aman,IT,2025-01-03,60000,3000,4,4.0,3.0,495000,61875.000000,8
2,103,Rahul,IT,2025-01-02,60000,4000,5,4.0,3.0,495000,61875.000000,8
4,105,Aman,IT,2025-01-01,60000,2500,6,4.0,3.0,495000,61875.000000,8
10,111,Rahul,IT,2025-01-03,60000,4500,7,4.0,3.0,495000,61875.000000,8
6,107,Rahul,IT,2025-01-01,50000,3500,8,8.0,4.0,495000,61875.000000,8

In [232]:
data = {
    'employee_id': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                    111, 112, 113, 114, 115],
    'employee': ['Aman', 'Priya', 'Rahul', 'Neha', 'Aman',
                 'Priya', 'Rahul', 'Neha', 'Aman', 'Priya',
                 'Rahul', 'Neha', 'Aman', 'Priya', 'Rahul'],
    'department': ['IT', 'HR', 'IT', 'HR', 'IT',
                   'HR', 'IT', 'HR', 'IT', 'HR',
                   'IT', 'HR', 'IT', 'HR', 'IT'],
    'date': ['2025-01-03', '2025-01-01', '2025-01-02',
             '2025-01-04', '2025-01-01', '2025-01-03',
             '2025-01-01', '2025-01-02', '2025-01-04',
             '2025-01-02', '2025-01-03', '2025-01-01',
             '2025-01-02', '2025-01-04', '2025-01-05'],
    'salary': [60000, 50000, 60000, 45000, 60000,
               55000, 50000, 45000, 70000, 50000,
               60000, 50000, 65000, 60000, 70000],
    'sales': [3000, 2000, 4000, 1500, 2500,
              3000, 3500, 2000, 5000, 2500,
              4500, 1800, 4000, 3500, 6000]
}

df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])

print(df)

    employee_id employee department       date  salary  sales
0           101     Aman         IT 2025-01-03   60000   3000
1           102    Priya         HR 2025-01-01   50000   2000
2           103    Rahul         IT 2025-01-02   60000   4000
3           104     Neha         HR 2025-01-04   45000   1500
4           105     Aman         IT 2025-01-01   60000   2500
5           106    Priya         HR 2025-01-03   55000   3000
6           107    Rahul         IT 2025-01-01   50000   3500
7           108     Neha         HR 2025-01-02   45000   2000
8           109     Aman         IT 2025-01-04   70000   5000
9           110    Priya         HR 2025-01-02   50000   2500
10          111    Rahul         IT 2025-01-03   60000   4500
11          112     Neha         HR 2025-01-01   50000   1800
12          113     Aman         IT 2025-01-02   65000   4000
13          114    Priya         HR 2025-01-04   60000   3500
14          115    Rahul         IT 2025-01-05   70000   6000

In [233]:
df = df.sort_values(['department', 'salary'])
df

    employee_id employee department       date  salary  sales
3           104     Neha         HR 2025-01-04   45000   1500
7           108     Neha         HR 2025-01-02   45000   2000
1           102    Priya         HR 2025-01-01   50000   2000
9           110    Priya         HR 2025-01-02   50000   2500
11          112     Neha         HR 2025-01-01   50000   1800
5           106    Priya         HR 2025-01-03   55000   3000
13          114    Priya         HR 2025-01-04   60000   3500
6           107    Rahul         IT 2025-01-01   50000   3500
0           101     Aman         IT 2025-01-03   60000   3000
2           103    Rahul         IT 2025-01-02   60000   4000
4           105     Aman         IT 2025-01-01   60000   2500
10          111    Rahul         IT 2025-01-03   60000   4500
12          113     Aman         IT 2025-01-02   65000   4000
8           109     Aman         IT 2025-01-04   70000   5000
14          115    Rahul         IT 2025-01-05   70000   6000

In [234]:
df['lag']=df.groupby('department')['salary'].shift(1)
df

    employee_id employee department       date  salary  sales      lag
3           104     Neha         HR 2025-01-04   45000   1500      NaN
7           108     Neha         HR 2025-01-02   45000   2000  45000.0
1           102    Priya         HR 2025-01-01   50000   2000  45000.0
9           110    Priya         HR 2025-01-02   50000   2500  50000.0
11          112     Neha         HR 2025-01-01   50000   1800  50000.0
5           106    Priya         HR 2025-01-03   55000   3000  50000.0
13          114    Priya         HR 2025-01-04   60000   3500  55000.0
6           107    Rahul         IT 2025-01-01   50000   3500      NaN
0           101     Aman         IT 2025-01-03   60000   3000  50000.0
2           103    Rahul         IT 2025-01-02   60000   4000  60000.0
4           105     Aman         IT 2025-01-01   60000   2500  60000.0
10          111    Rahul         IT 2025-01-03   60000   4500  60000.0
12          113     Aman         IT 2025-01-02   65000   4000  60000.0
8           109     Aman         IT 2025-01-04   70000   5000  65000.0
14          115    Rahul         IT 2025-01-05   70000   6000  70000.0

In [235]:
df['lead']=df.groupby('department')['salary'].shift(-1)
df

,employee_id,employee,department,date,salary,sales,lag,lead
3,104,Neha,HR,2025-01-04,45000,1500,NaN,45000.0
7,108,Neha,HR,2025-01-02,45000,2000,45000.0,50000.0
1,102,Priya,HR,2025-01-01,50000,2000,45000.0,50000.0
9,110,Priya,HR,2025-01-02,50000,2500,50000.0,50000.0
11,112,Neha,HR,2025-01-01,50000,1800,50000.0,55000.0
5,106,Priya,HR,2025-01-03,55000,3000,50000.0,60000.0
13,114,Priya,HR,2025-01-04,60000,3500,55000.0,NaN
6,107,Rahul,IT,2025-01-01,50000,3500,NaN,60000.0
0,101,Aman,IT,2025-01-03,60000,3000,50000.0,60000.0
2,103,Rahul,IT,2025-01-02,60000,4000,60000.0,60000.0
4,105,Aman,IT,2025-01-01,60000,2500,60000.0,60000.0
10,111,Rahul,IT,2025-01-03,60000,4500,60000.0,65000.0
12,113,Aman,IT,2025-01-02,65000,4000,60000.0,70000.0
8,109,Aman,IT,2025-01-04,70000,5000,65000.0,70000.0
14,115,Rahul,IT,2025-01-05,70000,6000,70000.0,NaN

In [236]:
df = df.sort_values(['department', 'salary'])
df

,employee_id,employee,department,date,salary,sales,lag,lead
3,104,Neha,HR,2025-01-04,45000,1500,NaN,45000.0
7,108,Neha,HR,2025-01-02,45000,2000,45000.0,50000.0
1,102,Priya,HR,2025-01-01,50000,2000,45000.0,50000.0
9,110,Priya,HR,2025-01-02,50000,2500,50000.0,50000.0
11,112,Neha,HR,2025-01-01,50000,1800,50000.0,55000.0
5,106,Priya,HR,2025-01-03,55000,3000,50000.0,60000.0
13,114,Priya,HR,2025-01-04,60000,3500,55000.0,NaN
6,107,Rahul,IT,2025-01-01,50000,3500,NaN,60000.0
0,101,Aman,IT,2025-01-03,60000,3000,50000.0,60000.0
2,103,Rahul,IT,2025-01-02,60000,4000,60000.0,60000.0
4,105,Aman,IT,2025-01-01,60000,2500,60000.0,60000.0
10,111,Rahul,IT,2025-01-03,60000,4500,60000.0,65000.0
12,113,Aman,IT,2025-01-02,65000,4000,60000.0,70000.0
8,109,Aman,IT,2025-01-04,70000,5000,65000.0,70000.0
14,115,Rahul,IT,2025-01-05,70000,6000,70000.0,NaN

In [237]:
df['running_total']=df.groupby('department')['salary'].cumsum()
df

,employee_id,employee,department,date,salary,sales,lag,lead,running_total
3,104,Neha,HR,2025-01-04,45000,1500,NaN,45000.0,45000
7,108,Neha,HR,2025-01-02,45000,2000,45000.0,50000.0,90000
1,102,Priya,HR,2025-01-01,50000,2000,45000.0,50000.0,140000
9,110,Priya,HR,2025-01-02,50000,2500,50000.0,50000.0,190000
11,112,Neha,HR,2025-01-01,50000,1800,50000.0,55000.0,240000
5,106,Priya,HR,2025-01-03,55000,3000,50000.0,60000.0,295000
13,114,Priya,HR,2025-01-04,60000,3500,55000.0,NaN,355000
6,107,Rahul,IT,2025-01-01,50000,3500,NaN,60000.0,50000
0,101,Aman,IT,2025-01-03,60000,3000,50000.0,60000.0,110000
2,103,Rahul,IT,2025-01-02,60000,4000,60000.0,60000.0,170000
4,105,Aman,IT,2025-01-01,60000,2500,60000.0,60000.0,230000
10,111,Rahul,IT,2025-01-03,60000,4500,60000.0,65000.0,290000
12,113,Aman,IT,2025-01-02,65000,4000,60000.0,70000.0,355000
8,109,Aman,IT,2025-01-04,70000,5000,65000.0,70000.0,425000
14,115,Rahul,IT,2025-01-05,70000,6000,70000.0,NaN,495000

In [241]:
df.drop(columns='sales',inplace=True)

In [242]:
df['running_avg']=df.groupby('department')['salary'].expanding().mean().round(1).reset_index(level=0, drop=True)
df

,employee_id,employee,department,date,salary,lag,lead,running_total,running_avg
3,104,Neha,HR,2025-01-04,45000,NaN,45000.0,45000,45000.0
7,108,Neha,HR,2025-01-02,45000,45000.0,50000.0,90000,45000.0
1,102,Priya,HR,2025-01-01,50000,45000.0,50000.0,140000,46666.7
9,110,Priya,HR,2025-01-02,50000,50000.0,50000.0,190000,47500.0
11,112,Neha,HR,2025-01-01,50000,50000.0,55000.0,240000,48000.0
5,106,Priya,HR,2025-01-03,55000,50000.0,60000.0,295000,49166.7
13,114,Priya,HR,2025-01-04,60000,55000.0,NaN,355000,50714.3
6,107,Rahul,IT,2025-01-01,50000,NaN,60000.0,50000,50000.0
0,101,Aman,IT,2025-01-03,60000,50000.0,60000.0,110000,55000.0
2,103,Rahul,IT,2025-01-02,60000,60000.0,60000.0,170000,56666.7
4,105,Aman,IT,2025-01-01,60000,60000.0,60000.0,230000,57500.0
10,111,Rahul,IT,2025-01-03,60000,60000.0,65000.0,290000,58000.0
12,113,Aman,IT,2025-01-02,65000,60000.0,70000.0,355000,59166.7
8,109,Aman,IT,2025-01-04,70000,65000.0,70000.0,425000,60714.3
14,115,Rahul,IT,2025-01-05,70000,70000.0,NaN,495000,61875.0